import jQuery from 'jquery'
// import bootstrap from 'bootstrap.js'
import main from './js/main'
// import image from 'sprite.png'
// import './css/sprite.css'
// import 'bootstrap.css'
import './css/sprite.css'
import './css/sprite62.css'
import './css/style.css'
main(jQuery)
